# Generated by Django 6.0.2 on 2026-04-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_rename_deadline_goal_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
